FROM balenalib/%%BALENA_MACHINE_NAME%%-node
RUN apt-get -q update && apt-get install -yq --no-install-recommends \
	build-essential python python3 \
	&& apt-get clean && rm -rf /var/lib/apt/lists/*

COPY . ./
RUN ls -lah
RUN npm install
ENV PORT 80
CMD ["npm", "start"]